import type { Metadata } from "next";
import { Montserrat, Mr_Dafoe } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  display: 'swap',
})

const mrDafoe = Mr_Dafoe({
  variable: "--font-mrDafoe",
  weight: "400",
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${mrDafoe.variable}`}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
