import type { Metadata } from "next";
import { Montserrat, Mr_Dafoe } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import FloatButtons from "@/components/floatButtons/floatButtons";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  display: 'swap',
  subsets: ['latin']
})

const mrDafoe = Mr_Dafoe({
  variable: "--font-mrDafoe",
  weight: "400",
  display: 'swap',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${mrDafoe.variable}`}>
        <div
          className="header"
        >
          <Header />
        </div>

        <div
          className="children"
        >
          {children}
        </div>

        <FloatButtons />

        <div
          className="footer"
        >
          <Footer />
        </div>
      </body>
    </html>
  );
}
